algorithm: Q_learning
environment: 
  id: FrozenLake-v1
  is_slippery: true
  map_name: 4x4

hyperparameters:
  strategy: v1
  exploration_strategy: epsilon_greedy
  potential_reward_shaping: false
  gamma: 0.95
  alpha: 0.8
  eps: 0.2
  render: true
  max_episode: 1500